interface FournisseurMapping {
    [key: string]: string;
  }
  
  const fournisseurMapping: FournisseurMapping = {
    '3RG': '3RG',
    'ABN': 'ABN Auto Parts',
    'AEC': 'AEC Auto Parts',
    'AHE': 'AHE',
    'ALF': 'Alfa Romeo',
    'ALK': 'Alkar',
    'AR': 'Arca',
    'AUT': 'Autolog',
    'BEH': 'Behr',
    'BEN': 'Bendix',
    'BER': 'Beru',
    'BGF': 'BGF',
    'BOC': 'Bocciolone',
    'BOS': 'Bosch',
    'BOU': 'Bougicord',
    'CAB': 'Cabor',
    'CAR': 'Cargo',
    'CHA': 'Champion',
    'CHK': 'Check',
    'CL': 'CL Brakes',
    'COR': 'Corteco',
    'CRE': 'Cреди',
    'DAY': 'Dayco',
    'DEN': 'Denso',
    'DIV': 'Divers',
    'DKM': 'DKM',
    'DLZ': 'DLZ',
    'DOG': 'Doga',
    'DOL': 'Dolu',
    'DON': 'Donna',
    'EAI': 'EAI',
    'ECS': 'ECS',
    'ELR': 'ElringKlinger',
    'ENG': 'Engineteam',
    'ESC': 'Escort',
    'FAC': 'Facet',
    'FAE': 'FAE',
    'FAR': 'Far',
    'FEB': 'Febi Bilstein',
    'FED': 'Federal-Mogul',
    'FER': 'Ferodo',
    'FIA': 'Fiat',
    'FRA': 'Fram',
    'FRP': 'FRP',
    'GAR': 'Garrett',
    'GAT': 'Gates',
    'GAU': 'Gauges',
    'GEO': 'Geofoto',
    'GKN': 'GKN',
    'GM': 'General Motors',
    'GOT': 'Goetze',
    'GRA': 'Graf',
    'GUI': 'Guibo',
    'HAS': 'Hasco',
    'HIT': 'Hitachi',
    'HUC': 'Huco',
    'HUG': 'Hugues',
    'ICA': 'ICA',
    'ICR': 'Intercooler',
    'IMP': 'Imperial',
    'ISU': 'Isuzu',
    'JAP': 'Japan Auto Parts',
    'JOI': 'Joints',
    'JUR': 'Jurid',
    'KAL': 'Kale',
    'KLA': 'KLA Motors',
    'KS': 'Kolbenschmidt',
    'KSS': 'KSS',
    'LOU': 'Louvers',
    'LPR': 'LPR',
    'LUK': 'LuK',
    'MAC': 'Macauto',
    'MAD': 'Madras',
    'MAH': 'Mahle',
    'MAP': 'Mapco',
    'MC': 'Motorcraft',
    'MCA': 'MCA Suspensions',
    'MCF': 'MCF',
    'MEC': 'Mecafilter',
    'MEI': 'Meistersatz',
    'MEK': 'Mekra',
    'MET': 'Metelli',
    'MIM': 'Mimparts',
    'MIS': 'Mistr',
    'MLI': 'Magli',
    'MOG': 'Moog',
    'MTA': 'MTA',
    'NAG': 'Nagares',
    'NAO': 'NAO',
    'NAR': 'Narva',
    'NGK': 'NGK',
    'NRF': 'NRF',
    'OCA': 'OCA',
    'OE': 'Original Equipment',
    'ORE': 'Oreille',
    'ORM': 'Orman Filtration',
    'PAY': 'Payen',
    'PEU': 'Peugeot',
    'PHI': 'Philips',
    'PN': 'PN Auto Parts',
    'REA': 'Reach Auto Parts',
    'REC': 'Record',
    'REN': 'Renault',
    'RIS': 'Riso',
    'RNA': 'RNA Automotive',
    'RTI': 'RTI Technologies',
    'RTS': 'RTS',
    'SAS': 'SAS Automotive',
    'SEI': 'Seiko Seiki',
    'SIM': 'Simco',
    'SIO': 'Sioux Tools',
    'SIS': 'Sisal',
    'SKF': 'SKF',
    'SNP': 'SNP',
    'SNR': 'SNR',
    'SOG': 'Sogefiflex',
    'SOP': 'Sopp',
    'SUD': 'Sudamericana de Rodamientos',
    'SUP': 'Suplex',
    'TAI': 'Taiho',
    'TAL': 'Talbot',
    'TC': 'Turbo Charger',
    'TEC': 'Tec Auto Parts',
    'TGF': 'TGF',
    'TT': 'TT Auto Parts',
    'TUR': 'Turbo',
    'VAL': 'Valeo',
    'VER': 'Vernet',
    'VIC': 'Victor Reinz',
    'VL': 'VL Auto Parts',
    'WAI': 'WAI Global',
    'WHI': 'Whi',
    'YEN': 'Yenmak',
    'ZEN': 'Zen',
    'ZM': 'ZM Automotive'
  };
  
  export function getFournisseurFullName(abbreviation: string): string {
    const fullName = fournisseurMapping[abbreviation.toUpperCase()];
    return fullName || abbreviation; // Return the original abbreviation if not found
  }